name: meditation_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  audioplayers: ^5.2.1
  path_provider: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

# Temporary override to ensure compatibility with Android Gradle Plugin (AGP) 8+
dependency_overrides:
  plugin_platform_interface: ^2.1.4
  path_provider_android: ^2.0.30

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/musics/
